name: Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # tag=v2.2.4
              id: pnpm-install
              with:
                  version: 8
                  run_install: false
            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
            - uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-store-
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run build
              run: pnpm build

    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # tag=v2.2.4
              id: pnpm-install
              with:
                  version: 8
                  run_install: false
            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
            - uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-store-
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run Lint
              run: pnpm eslint --ext .ts,.tsx,.vue --no-error-on-unmatched-pattern --ignore-path .gitignore .
